Repository canonical/dqlite.io, pull requests merged in 2019-09, with the labels that each got.

#22 Change PPA name
  index.html
Labels: Review: Code +1

#24 Fix typo in FAQ
  docs/faq.md
Labels: Review: Code +1

#25 Change reference to OS X to macOS
  docs/faq.md
Labels: Review: Code +1

#26 Add GitHub buttons to site
  _layouts/base.html
  index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#27 Fix capitalisation
  index.html
Labels: Good first issue 🔰, Review: Code +1
