Repository canonical/dqlite.io, pull requests merged in 2020-06, with the labels that each got.

#57 Update github actions
  .github/workflows/pr.yml
Labels: Review: Code +1

#58 Update webpack config
  .eslintrc.js
  .github/workflows/pr.yml
  .webpack/entry.js
  .webpack/rules.js
  package.json
  static/js/sample.test.js
  webpack.config.js
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#59 Fix webpack config includes
  webpack.config.entry.js
  webpack.config.js
  webpack.config.rules.js
Labels: Review: Code needed, Review: QA needed

#60 Add k8s configuration in deploy/site.yaml
  README.md
  deploy/site.yaml
Labels: Review: Code +1

#61 Remove CircleCI badge
  README.md
Labels: Review: Code +1
