Repository canonical/dqlite.io, pull requests merged in 2020-04, with the labels that each got.

#43 Disable docker updates from renovate
  Dockerfile
  renovate.json
Labels: Review: Code needed

#47 Update the license mentioned in the home page, since it has changed
  index.html
Labels: Review: Code +1

#45 Convert to flask
  .circleci/config.yml
  .env
  .eslintrc.js
  .github/pull_request_template.md
  .github/workflows/pr.yml
  .gitignore
  .prettierignore
  .stylelintrc
  Dockerfile
  Gemfile
  Gemfile.lock
  _config.yml
  _includes/_docs-navigation.html
  _layouts/base.html
  _layouts/docs.html
  _sass/_docs-layout.scss
  _status/check.html
  docs/faq.md
  docs/index.md
  docs/protocol.md
  entrypoint
  keyring.deb
  nginx.conf
  package.json
  requirements.txt
  run
  static/js/base.js
  static/js/global-nav.js
  static/sass/_settings.scss
  static/sass/styles.scss
  templates/404.html
  templates/500.html
  templates/base_layout.html
  templates/docs/base_docs.html
  templates/docs/faq.html
  templates/docs/index.html
  templates/docs/protocol.html
  templates/index.html
  templates/partial/_footer.html
  templates/partial/_navigation.html
  tests/__init__.py
  tests/test_routes.py
  webapp/__init__.py
  webapp/app.py
  webpack.config.js
  yarn.lock
Labels: Review: Code needed, Review: QA +1

#49 Add discourse docs module
  requirements.txt
  static/js/highlight.pack.js
  static/sass/_layout_docs.scss
  static/sass/styles.scss
  templates/docs/base_docs.html
  templates/docs/document.html
  templates/docs/faq.html
  templates/docs/index.html
  templates/docs/protocol.html
  templates/docs/search.html
  webapp/app.py
Labels: Review: Code +1, Review: QA +1
