Repository canonical/dqlite.io, pull requests merged in 2023-11, with the labels that each got.

#267 Update rockcraft and gitignore files
  .gitignore
  rockcraft.yaml
Labels: Review: Code +1

#269 Update rockcraft.yaml
  rockcraft.yaml
Labels: Review: Code needed

#271 Update site.yaml
  konf/site.yaml
Labels: Review: Code +1, Review: QA +1

#272 Bump canonicalwebteam.discourse to 5.4.7
  requirements.txt
Labels: Review: Code +1, Review: QA +1
